[workspace]
channels = ["conda-forge", "bioconda"]
name = "SAIGEQTL"
platforms = ["linux-64", "osx-64"]
version = "0.3.2"

[tasks]
[tasks.install-abess]
cmd = "R -q -e 'install.packages(\"abess\", repos=\"https://cloud.r-project.org\")'"

[dependencies]
boost-cpp = "*"
cget = "*"
openblas = "*"
r = "*"
r-optparse="*"
r-rcpp="*"
r-brglm2="*"
r-metafor="*"
"r-data.table" = "*"
r-dplyr = "*"
r-qqman = "*"
bioconductor-snpstats = "*"
r-ggplot2 = ">=4.0.2,<5"
r-stringr = ">=1.6.0,<2"
r-rcpparmadillo = ">=15.2.3_1,<16"
r-styler = ">=1.11.0,<2"

