[workspace]
channels = ["conda-forge", "bioconda"]
name = "SAIGEQTL"
platforms = ["linux-64", "osx-64"]
version = "0.3.2"

[tasks]
[tasks.install-abess]
cmd = "R -q -e 'install.packages(\"abess\", repos=\"https://cloud.r-project.org\")'"

[dependencies]
boost-cpp = "*"
cget = "*"
openblas = "*"
r = "*"
r-optparse="*"
r-rcpp="*"
r-brglm2="*"
r-metafor="*"
"r-data.table" = "*"
r-dplyr = "*"
r-qqman = "*"
bioconductor-snpstats = "*"
