#' Run PALM summary statistics for genotype inputs
#'
#' Reads genotype data from PLINK or VCF input, applies a pre-fitted PALM null
#' model, and writes per-phenotype summary statistics (one file per phenotype).
#' VCF input is read directly.
#'
#' @param genoFile Path to genotype input. If the path ends with
#'   `.vcf`, `.vcf.gz`, or `.vcf.bgz`, VCF input is assumed. Otherwise it is
#'   treated as a PLINK prefix without extension.
#' @param nullModelPrefix Prefix for the fitted null model generated by Step1.
#'   The function reads `<nullModelPrefix>.rda`.
#' @param outputPrefix Base prefix for Step2 summary result files. The
#'   function normalizes a trailing underscore when present, then writes one file per feature as
#'   `<outputPrefix>_chr<chrom>_<feature>.txt` when `chrom` is set, or
#'   `<outputPrefix>_allchr_<feature>.txt` when `chrom` is `NULL`.
#' @param vcfField Optional VCF FORMAT field override. By default the reader
#'   auto-detects and prefers `"DS"` when present, otherwise falls back to
#'   `"GT"`. Supported explicit values are `"DS"` and `"GT"`.
#' @param chrom Optional chromosome filter (numeric or string like `"chr1"`).
#'   Use `NULL` to keep all chromosomes.
#' @param featureList Optional feature IDs to keep from the Step1 null model.
#'   Accepts either a character vector or a single comma-separated string.
#'   Use `NULL` (default) to keep all modeled features.
#' @param minMAF Optional minimum minor allele frequency threshold used to
#'   filter SNPs before running `PALM::palm.get.summary()`. Defaults to `0.05`.
#'   Use `0` to disable MAF filtering.
#' @param minMAC Optional minimum minor allele count threshold used to filter
#'   SNPs before running `PALM::palm.get.summary()`. Defaults to `5`. Use `0`
#'   to disable MAC filtering.
#' @param maxMissing Maximum per-SNP missing genotype rate. SNPs above this
#'   threshold are removed before imputation and association testing. Defaults
#'   to `0.15`. Use `1` to disable missingness filtering.
#' @param impute_method Missing genotype imputation method for SNPs that pass
#'   `maxMissing`. Supported values are `"best_guess"` (most frequent observed
#'   genotype, with mean dosage tie-break), `"mean"` (mean observed dosage), and
#'   `"minor"` (homozygous minor-allele genotype inferred from observed allele
#'   frequency). Use `"false"` to skip imputation; remaining missing genotype
#'   values are left as missing after the `maxMissing` SNP-level filter.
#'   Defaults to `"best_guess"`.
#' @param snpInfoFile Optional output path for SNP sample count and allele
#'   frequency computed from the Step2 genotype matrix after NULL-model sample
#'   alignment, optional chromosome subsetting, missingness filtering,
#'   imputation, and minMAF/minMAC filtering. This describes the final SNP set
#'   used for Step2.1 association testing; the `MissingRate` column is computed
#'   after missingness filtering and before imputation. Use `NULL` (default) to
#'   skip writing this file.
#' @param correct Passed to `PALM::palm.get.summary()`; defaults to `"NULL"`.
#'
#' @return Invisibly returns a character vector of written file paths.
#' @export
getSummary <- function(genoFile,
                       nullModelPrefix,
                       outputPrefix,
                       vcfField = NULL,
                       chrom = NULL,
                       featureList = NULL,
                       minMAF = 0.05,
                       minMAC = 5,
                       maxMissing = 0.15,
                       impute_method = "best_guess",
                       snpInfoFile = NULL,
                       correct = NULL) {
  if (!requireNamespace("PALM", quietly = TRUE)) {
    stop("Package 'PALM' is required but not installed.")
  }
  if (!requireNamespace("snpStats", quietly = TRUE)) {
    stop("Package 'snpStats' is required but not installed.")
  }

  if (missing(genoFile) || !nzchar(genoFile)) {
    stop("'genoFile' must be provided.")
  }
  if (missing(nullModelPrefix) || !nzchar(nullModelPrefix)) {
    stop("'nullModelPrefix' must be provided.")
  }
  null_model_file <- nullModelPrefix
  if (grepl("\\.rda$", null_model_file, ignore.case = TRUE)) {
    null_model_file <- sub("\\.rda$", "", null_model_file, ignore.case = TRUE)
    message("nullModelPrefix should not include .rda; normalizing to prefix: ", null_model_file)
  }
  null_model_file <- paste0(null_model_file, ".rda")
  if (!file.exists(null_model_file)) {
    stop("NULL model file not found: ", null_model_file)
  }
  if (missing(outputPrefix) || !nzchar(outputPrefix)) {
    stop("'outputPrefix' must be provided.")
  }
  outputPrefix <- sub("_+$", "", outputPrefix)
  if (!is.numeric(minMAF) || length(minMAF) != 1L || is.na(minMAF) || minMAF < 0 || minMAF > 0.5) {
    stop("'minMAF' must be a single numeric value between 0 and 0.5.")
  }
  if (!is.numeric(minMAC) || length(minMAC) != 1L || is.na(minMAC) || minMAC < 0 || minMAC != as.integer(minMAC)) {
    stop("'minMAC' must be a single non-negative integer value.")
  }
  if (!is.numeric(maxMissing) || length(maxMissing) != 1L || is.na(maxMissing) || maxMissing < 0 || maxMissing > 1) {
    stop("'maxMissing' must be a single numeric value between 0 and 1.")
  }
  impute_method <- tolower(trimws(as.character(impute_method)[1]))
  if (is.na(impute_method) || !nzchar(impute_method) || identical(toupper(impute_method), "NULL")) {
    impute_method <- "best_guess"
  }
  if (!impute_method %in% c("best_guess", "mean", "minor", "false")) {
    stop("'impute_method' must be one of 'best_guess', 'mean', 'minor', or 'false'.")
  }
  output_dir <- dirname(outputPrefix)
  if (!output_dir %in% c("", ".")) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }

  genoFormat <- infer_geno_format(genoFile)
  message("Genotype input format inferred from genoFile: ", genoFormat)

  env <- new.env()
  load(null_model_file, envir = env) # load modglmm
  if (!exists("modglmm", envir = env)) {
    stop("Object 'modglmm' not found in ", null_model_file)
  }
  modglmm <- env$modglmm
  message("Loaded NULL model from ", null_model_file)

  normalize_col_list <- function(x, arg_name) {
    if (is.null(x)) {
      return(NULL)
    }
    if (length(x) == 1L) {
      x <- trimws(strsplit(x, ",", fixed = TRUE)[[1]])
    } else {
      x <- trimws(as.character(x))
    }
    x <- x[nzchar(x)]
    if (!length(x)) {
      stop("'", arg_name, "' did not contain any valid column names.")
    }
    x
  }

  subset_null_model_features <- function(null_obj, feature_ids) {
    if (is.null(feature_ids)) {
      return(null_obj)
    }
    feature_by_study <- lapply(names(null_obj), function(d) colnames(null_obj[[d]]$Y_I))
    names(feature_by_study) <- names(null_obj)
    feature_union <- sort(unique(unlist(feature_by_study, use.names = FALSE)))
    missing_features <- setdiff(feature_ids, feature_union)
    if (length(missing_features) > 0L) {
      stop(
        "Requested feature(s) not found in NULL model: ",
        paste(missing_features, collapse = ", ")
      )
    }

    null_subset <- null_obj
    for (d in names(null_subset)) {
      keep <- intersect(feature_ids, colnames(null_subset[[d]]$Y_I))
      if (!length(keep)) {
        stop(
          "Requested feature(s) are absent from study '", d,
          "' in the NULL model after prevalence filtering."
        )
      }
      null_subset[[d]]$Y_I <- null_subset[[d]]$Y_I[, keep, drop = FALSE]
      null_subset[[d]]$Y_R <- null_subset[[d]]$Y_R[, keep, drop = FALSE]
    }
    null_subset
  }

  extract_null_row_ids <- function(null_obj) {
    if (!is.list(null_obj) || length(null_obj) < 1L) {
      return(NULL)
    }
    first_study <- null_obj[[1]]
    if (!is.list(first_study)) {
      return(NULL)
    }
    for (candidate in c("Z", "Y_I", "Y_R")) {
      mat <- first_study[[candidate]]
      ids <- rownames(mat)
      if (!is.null(ids) && length(ids) > 0L) {
        return(ids)
      }
    }
    NULL
  }

  extract_null_subject_ids <- function(null_obj, row_ids) {
    subject_ids <- attr(null_obj, "subject_ids", exact = TRUE)
    if (!is.null(subject_ids) && length(subject_ids) == length(row_ids)) {
      return(as.character(subject_ids))
    }
    row_ids
  }

  null_row_ids <- extract_null_row_ids(modglmm)
  null_sample_ids <- if (is.null(null_row_ids)) NULL else extract_null_subject_ids(modglmm, null_row_ids)
  null_cluster_ids <- attr(modglmm, "cluster_ids", exact = TRUE)
  if (!is.null(null_cluster_ids)) {
    null_cluster_ids <- as.character(null_cluster_ids)
    if (is.null(names(null_cluster_ids)) && !is.null(null_row_ids) && length(null_cluster_ids) == length(null_row_ids)) {
      names(null_cluster_ids) <- null_row_ids
    }
  }
  if (is.null(null_row_ids)) {
    message("Could not infer subject IDs from NULL model; using genotype rows as-is.")
  } else {
    message("NULL model row count: ", length(null_sample_ids))
    if (anyDuplicated(null_sample_ids) > 0L) {
      message("Repeated subject IDs detected in NULL model; Step2.1 will expand genotype rows and use clustering.")
    }
  }

  featureList <- normalize_col_list(featureList, "featureList")
  if (is.null(featureList)) {
    message("Feature filter disabled: using all modeled features.")
  } else {
    message("Feature filter enabled: requested ", length(featureList), " feature(s).")
    modglmm <- subset_null_model_features(modglmm, featureList)
    message(
      "NULL model after feature filtering: ",
      paste(
        sprintf("%s=%d", names(modglmm), vapply(modglmm, function(x) ncol(x$Y_I), integer(1))),
        collapse = "; "
      ),
      " feature(s) per study."
    )
  }

  # normalize chrom input: treat "" or "NULL" as NULL
  if (!is.null(chrom) && is.character(chrom)) {
    if (!nzchar(chrom) || toupper(chrom) == "NULL") chrom <- NULL
  }
  if (is.null(chrom)) {
    message("Chromosome filter disabled: using all SNPs.")
  } else {
    message("Chromosome filter enabled: requested chromosome ", chrom)
  }
  summary_suffix <- "allchr"
  if (minMAF > 0) {
    message("MAF filter enabled: minMAF=", minMAF)
  } else {
    message("MAF filter disabled: minMAF=0")
  }
  if (minMAC > 0) {
    message("MAC filter enabled: minMAC=", minMAC)
  } else {
    message("MAC filter disabled: minMAC=0")
  }
  if (maxMissing < 1) {
    message("Missingness filter enabled: maxMissing=", maxMissing)
  } else {
    message("Missingness filter disabled: maxMissing=1")
  }
  message("Missing genotype imputation method: ", impute_method)
  message(
    "Genotype QC order: load genotype -> align NULL-model samples -> chromosome filter -> ",
    "compute MissingRate -> maxMissing filter -> impute unless impute_method=false -> ",
    "minMAF/minMAC filter -> write snpInfoFile -> PALM summary."
  )
  if (is.null(correct)) {
    message("Compositional correction disabled: correct=NULL")
  } else {
    message("Compositional correction enabled: correct=", correct)
  }
  repeated_null_subjects <- !is.null(null_sample_ids) && anyDuplicated(null_sample_ids) > 0L
  use_cluster <- FALSE
  cluster <- NULL
  cluster_source <- NULL
  if (!is.null(null_cluster_ids)) {
    cluster <- null_cluster_ids
    cluster_source <- paste0("Step1 covFile clusterCol", {
      cluster_col <- attr(modglmm, "cluster_col", exact = TRUE)
      if (!is.null(cluster_col) && nzchar(cluster_col)) paste0(" '", cluster_col, "'") else ""
    })
    use_cluster <- TRUE
    message("Using cluster IDs stored in NULL model from ", cluster_source, ".")
  }
  chr_map <- NULL
  if (identical(genoFormat, "vcf")) {
    vcf_input <- read_vcf_genotypes(genoFile, vcfField = vcfField)
    geno <- vcf_input$geno
    chr_map <- as.character(vcf_input$map$chromosome)
  } else {
    geno_input <- prepare_plink_input(
      genoFile = genoFile,
      tempLabel = "summary"
    )
    if (length(geno_input$cleanup) > 0L) {
      on.exit(unlink(geno_input$cleanup, force = TRUE), add = TRUE)
    }
    genoPrefix <- geno_input$prefix

    bed <- paste0(genoPrefix, ".bed")
    bim <- paste0(genoPrefix, ".bim")
    fam <- paste0(genoPrefix, ".fam")
    for (f in c(bed, bim, fam)) if (!file.exists(f)) stop("Missing PLINK file: ", f)

    if (is.null(cluster)) {
      message("Reading PLINK .fam file for cluster info.")
      fam_data <- utils::read.table(fam, stringsAsFactors = FALSE)
      colnames(fam_data) <- c("FID", "IID", "PID", "MID", "SEX", "PHENO")
      cluster <- as.character(fam_data$FID)
      names(cluster) <- fam_data$IID
      cluster_source <- "PLINK FID"
      invalid_fid <- all(is.na(cluster) | !nzchar(trimws(cluster)) | cluster == "0") ||
        length(unique(cluster[!is.na(cluster) & nzchar(trimws(cluster))])) <= 1L
      if (invalid_fid) {
        if (repeated_null_subjects) {
          message("PLINK FID values are not informative. Longitudinal clustering will use subject ID.")
          cluster <- NULL
          cluster_source <- NULL
        } else {
          message("PLINK FID values are all 0, missing, or identical. No family/pedigree clustering will be used.")
          cluster <- NULL
          cluster_source <- NULL
        }
      } else {
        use_cluster <- TRUE
        message("Using valid PLINK .fam FID values for family/pedigree clustering.")
      }
    }

    plink <- snpStats::read.plink(bed, bim, fam)
    G <- plink$genotypes
    iid <- rownames(G)
    if (is.null(iid)) stop("No rownames (IID) found in genotype matrix from read.plink().")

    geno <- as(G, "numeric")
    rownames(geno) <- iid
    colnames(geno) <- colnames(G)
    chr_map <- as.character(plink$map$chromosome)
    message("Loaded genotype matrix: ", nrow(geno), " samples x ", ncol(geno), " SNPs before chromosome filtering.")
  }

  if (!is.null(null_sample_ids)) {
    missing_null_ids <- setdiff(null_sample_ids, rownames(geno))
    if (length(missing_null_ids) > 0L) {
      stop(
        "Some NULL-model samples are missing from genotype input: ",
        paste(utils::head(missing_null_ids, 5), collapse = ", ")
      )
    }
    geno <- geno[null_sample_ids, , drop = FALSE]
    if (!is.null(null_row_ids) && length(null_row_ids) == nrow(geno)) {
      rownames(geno) <- null_row_ids
    }
    if (!is.null(cluster)) {
      if (!is.null(null_row_ids) && all(null_row_ids %in% names(cluster))) {
        cluster <- cluster[null_row_ids]
      } else {
        missing_cluster_ids <- setdiff(null_sample_ids, names(cluster))
        if (length(missing_cluster_ids) > 0L) {
          stop(
            "Some NULL-model samples are missing from cluster data: ",
            paste(utils::head(missing_cluster_ids, 5), collapse = ", ")
          )
        }
        cluster <- cluster[null_sample_ids]
      }
      if (!is.null(null_row_ids) && length(null_row_ids) == length(cluster)) {
        names(cluster) <- null_row_ids
      }
      if (any(is.na(cluster) | !nzchar(trimws(cluster)))) {
        stop("Cluster data contains missing or empty values after aligning to NULL-model samples.")
      }
    } else if (repeated_null_subjects) {
      cluster <- null_sample_ids
      names(cluster) <- if (!is.null(null_row_ids)) null_row_ids else null_sample_ids
      cluster_source <- "subject ID"
      use_cluster <- TRUE
    }
    message("Genotype matrix after aligning/expanding to NULL model rows: ", nrow(geno), " rows x ", ncol(geno), " SNPs.")
  } else if (!is.null(cluster)) {
    missing_cluster_ids <- setdiff(rownames(geno), names(cluster))
    if (length(missing_cluster_ids) > 0L) {
      stop(
        "Some genotype samples are missing from cluster data: ",
        paste(utils::head(missing_cluster_ids, 5), collapse = ", ")
      )
    }
    cluster <- cluster[rownames(geno)]
    if (any(is.na(cluster))) {
      stop("Cluster data contains NA values after aligning to genotype samples.")
    }
  }

  # Subset for quick testing (every 10th SNP)
  # geno <- geno[, seq(1, ncol(geno), by = 10), drop = FALSE]

  # --------------------------
  # Subset by chromosome if specified
  # --------------------------
  if (!is.null(chrom) && toupper(chrom) != "NULL") {
    message("Subsetting genotype data for chromosome: ", chrom)
    chrom <- sub("^chr", "", chrom, ignore.case = TRUE)
    if (!grepl("^([1-9]|1[0-9]|2[0-2])$", chrom)) {
      stop("Step2 summary naming currently supports only chromosomes 1-22 or NULL. Received: ", chrom)
    }
    summary_suffix <- paste0("chr", chrom)

    chr_map <- sub("^chr", "", chr_map, ignore.case = TRUE)
    keep <- which(chr_map == chrom)

    if (length(keep) == 0L) stop("No SNPs found for --chrom=", chrom)
    geno <- geno[, keep, drop = FALSE]
    message("Genotype matrix after chromosome filtering: ", nrow(geno), " samples x ", ncol(geno), " SNPs.")
  }

  missing_rate <- colMeans(is.na(geno))
  message(
    "Computed per-SNP MissingRate before imputation: min/median/max = ",
    sprintf("%.4f", min(missing_rate, na.rm = TRUE)), "/",
    sprintf("%.4f", stats::median(missing_rate, na.rm = TRUE)), "/",
    sprintf("%.4f", max(missing_rate, na.rm = TRUE))
  )
  if (maxMissing < 1) {
    keep <- which(!is.na(missing_rate) & missing_rate <= maxMissing)
    if (length(keep) == 0L) {
      stop("No SNPs remain after applying missingness filter (--maxMissing=", maxMissing, ").")
    }
    message(
      "Genotype matrix after missingness filtering: ", nrow(geno), " samples x ", length(keep),
      " SNPs (removed ", ncol(geno) - length(keep), ")."
    )
    geno <- geno[, keep, drop = FALSE]
    missing_rate <- missing_rate[keep]
  }
  missing_rate_for_info <- missing_rate

  na_count <- sum(is.na(geno))
  if (na_count > 0L && identical(impute_method, "false")) {
    message(
      "Missing genotype imputation disabled by impute_method=false; retaining ",
      na_count,
      " missing genotype value(s)."
    )
  } else if (na_count > 0L) {
    message("Imputing ", na_count, " missing genotype value(s) using method: ", impute_method)
    for (j in seq_len(ncol(geno))) {
      miss <- is.na(geno[, j])
      if (!any(miss)) {
        next
      }
      observed <- geno[!miss, j]
      if (!length(observed)) {
        stop("SNP has all missing genotypes after missingness filtering: ", colnames(geno)[j])
      }
      mean_dosage <- mean(observed)
      fill <- switch(
        impute_method,
        mean = mean_dosage,
        best_guess = {
          rounded <- pmin(2, pmax(0, round(observed)))
          tab <- table(factor(rounded, levels = c(0, 1, 2)))
          candidates <- as.numeric(names(tab)[tab == max(tab)])
          candidates[which.min(abs(candidates - mean_dosage))]
        },
        minor = {
          allele_freq <- mean_dosage / 2
          if (is.na(allele_freq)) {
            stop("Cannot infer minor allele for SNP: ", colnames(geno)[j])
          }
          if (allele_freq <= 0.5) 2 else 0
        }
      )
      geno[miss, j] <- fill
    }
    if (anyNA(geno)) {
      stop("Missing genotype imputation failed; NA values remain in genotype matrix.")
    }
  } else {
    message("No missing genotype values detected after missingness filtering; imputation skipped.")
  }

  if (minMAF > 0 || minMAC > 0) {
    allele_freq <- colMeans(geno, na.rm = TRUE) / 2
    maf <- pmin(allele_freq, 1 - allele_freq)
    called_alleles <- 2 * colSums(!is.na(geno))
    mac <- pmin(colSums(geno, na.rm = TRUE), called_alleles - colSums(geno, na.rm = TRUE))
    keep <- rep(TRUE, ncol(geno))
    if (minMAF > 0) {
      keep <- keep & !is.na(maf) & maf >= minMAF
    }
    if (minMAC > 0) {
      keep <- keep & !is.na(mac) & mac >= minMAC
    }
    keep <- which(keep)
    if (length(keep) == 0L) {
      stop("No SNPs remain after applying SNP filters (--minMAF=", minMAF, ", --minMAC=", minMAC, ").")
    }
    message(
      "Genotype matrix after MAF/MAC filtering: ", nrow(geno), " samples x ", length(keep),
      " SNPs (removed ", ncol(geno) - length(keep), ")."
    )
    geno <- geno[, keep, drop = FALSE]
    missing_rate_for_info <- missing_rate_for_info[keep]
  }

  if (!is.null(snpInfoFile) && nzchar(snpInfoFile)) {
    message(
      "Generating SNPInfo from the final Step2.1 genotype matrix after sample alignment",
      if (!is.null(chrom) && toupper(chrom) != "NULL") " and chromosome filtering" else "",
      ", missingness filtering, imputation, minMAF, and minMAC filtering. MissingRate is computed after missingness filtering and before imputation. Output path: ",
      snpInfoFile
    )
    snp_stats <- snp_info_from_geno_matrix(
      geno,
      snp_ids = colnames(geno),
      missing_rate = missing_rate_for_info
    )
    dir.create(dirname(snpInfoFile), recursive = TRUE, showWarnings = FALSE)
    data.table::fwrite(
      snp_stats,
      file = snpInfoFile,
      sep = "\t",
      quote = FALSE,
      na = "NA"
    )
    message("SNPInfo finished: ", nrow(snp_stats), " SNP(s) written to ", snpInfoFile)
  } else {
    message("SNPInfo skipped: snpInfoFile is NULL.")
  }


  # # Save dosage matrix
  # write.table(
  #   geno,
  #   file = file.path(output_prefix, "geno_allele2.txt"),
  #   sep = "\t",
  #   quote = FALSE,
  #   col.names = NA
  # )
  # cat("Wrote full allele.2 dosage matrix to: ",
  #     file.path(output_prefix, "geno_allele2_012_full.txt"), "\n"
  # )

  # ---------- run palm.get.summary ----------
  if (is.null(cluster)) {
    use_cluster <- FALSE
  }
  if (!use_cluster) {
    message("No cluster provided; running palm.get.summary without cluster.")
    res <- PALM::palm.get.summary(
      null.obj = modglmm,
      covariate.interest = geno,
      correct = correct
    )
  } else {
    message(
      "Cluster provided; running palm.get.summary with cluster",
      if (!is.null(cluster_source)) paste0(" (", cluster_source, ")") else "",
      "."
    )
    # print some cluster IDs
    uclust <- unique(cluster)
    message("Unique cluster IDs: ", length(uclust))
    max_print <- 10
    if (length(uclust) <= max_print) {
      print(uclust)
    } else {
      print(uclust[1:max_print])
      message("... (", length(uclust) - max_print, " more clusters omitted)")
    }

    tab <- table(cluster)
    message(
      "Cluster size (min/median/max): ",
      min(tab), "/", as.numeric(stats::median(tab)), "/", max(tab)
    )

    res <- PALM::palm.get.summary(
      null.obj = modglmm,
      covariate.interest = geno,
      correct = correct,
      cluster = cluster
    )
  }

  # ----------------------------
  # Write results to files (one per phenotype)
  # ----------------------------
  message("Writing results in split files by phenotype.")

  stopifnot(length(res) >= 1)
  study_names <- names(res)
  if (is.null(study_names) || any(study_names == "")) study_names <- paste0("Study", seq_along(res))
  names(res) <- study_names

  res_df_list <- lapply(study_names, function(d) {
    est_df <- as.data.frame(res[[d]]$est, check.names = FALSE)
    se_df <- as.data.frame(res[[d]]$stderr, check.names = FALSE)

    colnames(est_df) <- paste0(d, ".est.", colnames(est_df))
    colnames(se_df) <- paste0(d, ".stderr.", colnames(se_df))

    n_df <- data.frame(tmp = res[[d]]$n)
    colnames(n_df) <- paste0(d, ".n")

    cbind(est_df, se_df, n_df)
  })

  res <- res_df_list[[1]]
  if (length(res_df_list) > 1) {
    for (i in 2:length(res_df_list)) {
      # feature rows align (usually rownames are feature IDs); if not aligned, merge by rownames
      res <- cbind(res, res_df_list[[i]])
    }
  }

  # inherit rownames（feature IDs）
  rownames(res) <- rownames(res_df_list[[1]])


  # Automatically infer the study prefix (usually "Study")
  prefix <- sub("\\.est\\..*$", "", grep("\\.est\\.", colnames(res), value = TRUE)[1])
  if (is.na(prefix) || prefix == "") prefix <- "Study"

  est_pat <- paste0("^", prefix, "\\.est\\.")
  stderr_pat <- paste0("^", prefix, "\\.stderr\\.")

  est_cols <- grep(est_pat, colnames(res), value = TRUE)
  stderr_cols <- grep(stderr_pat, colnames(res), value = TRUE)

  if (length(est_cols) == 0 || length(stderr_cols) == 0) {
    stop(
      "Cannot find est/stderr columns in res. Example colnames(res): ",
      paste(head(colnames(res), 5), collapse = ", ")
    )
  }

  snp_est <- sub(est_pat, "", est_cols)
  snp_stderr <- sub(stderr_pat, "", stderr_cols)
  common_snp <- intersect(snp_est, snp_stderr)
  if (length(common_snp) == 0) stop("No matched SNPs between est and stderr columns.")

  # keep SNP order as in est columns
  common_snp <- snp_est[snp_est %in% common_snp]
  est_map <- setNames(est_cols, snp_est)
  stderr_map <- setNames(stderr_cols, snp_stderr)

  if (is.null(rownames(res)) || any(rownames(res) == "")) {
    stop("res has no rownames (phenotype names). Please ensure rownames(res)=pheno names.")
  }
  message("Writing ", nrow(res), " per-phenotype result file(s).")

  output_prefix <- paste0(outputPrefix, "_", summary_suffix)
  out_dir <- dirname(output_prefix)
  dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
  summary_n <- as.integer(nrow(geno))

  out_paths <- character(0)
  for (pheno in rownames(res)) {
    out <- data.frame(
      SNP = common_snp,
      est = as.numeric(res[pheno, est_map[common_snp], drop = TRUE]),
      stderr = as.numeric(res[pheno, stderr_map[common_snp], drop = TRUE]),
      check.names = FALSE
    )

    ## compute p-value
    # out$stat  <- out$est / out$stderr
    # out$pval <- 2 * pnorm(-abs(out$stat))
    out$pval <- 1 - pchisq((out$est / out$stderr)^2, df = 1)


    ## ----------------------------
    ## Post-process SNP format and derive CHR/POS
    ## ----------------------------

    # 1) Replace "." with ":" in SNP (e.g., chr1.1119172.G.A -> chr1:1119172:G:A)
    out$SNP <- gsub("\\.", ":", out$SNP)

    # 2) Parse CHR and POS from SNP (expects chr:pos:...)
    parts <- data.table::tstrsplit(out$SNP, ":", fixed = TRUE)
    if (length(parts) < 2) {
      stop("SNP format invalid after conversion; expected at least chr:pos:... (e.g., chr1:12345:A:G)")
    }

    chr_raw <- parts[[1]]
    pos_raw <- parts[[2]]

    # 3) Clean chromosome labels and convert to integer codes
    chr_clean <- sub("^chr", "", chr_raw, ignore.case = TRUE)
    chr_clean[chr_clean %in% c("X", "x")] <- "23"
    chr_clean[chr_clean %in% c("Y", "y")] <- "24"
    chr_clean[chr_clean %in% c("MT", "Mt", "mt", "M", "m")] <- "25"

    out$CHR <- suppressWarnings(as.integer(chr_clean))
    out$POS <- suppressWarnings(as.integer(pos_raw))
    out$N <- summary_n

    # (Optional) Reorder columns
    out <- out[, c("SNP", "CHR", "POS", "N", "est", "stderr", "pval")]


    out_file <- paste0(output_prefix, "_", pheno, ".txt")

    write.table(out,
      file = out_file, sep = "\t",
      quote = FALSE, row.names = FALSE, col.names = TRUE
    )
    out_paths <- c(out_paths, out_file)
  }

  message(
    "Done. Wrote ", length(out_paths),
    " file(s) named like ", output_prefix, "_<feature>.txt"
  )
  invisible(out_paths)
}
